apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache-php-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        name: apache-php-app
        image: radumatei/apache-php
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-php-internal-service
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
